/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.volmyr.gradle_plugins.utils

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

/**
 * A simple unit test for the 'com.volmyr.gradle_plugins.utils.greeting' plugin.
 */
class GradleUtilsPluginPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.volmyr.gradle_plugins.utils.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
